#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "============================================"
echo "  LucidLink Workspace Manager — Setup"
echo "============================================"
echo ""

if [ -f .env ]; then
    echo "Found existing .env file."
    read -rp "Overwrite it? [y/N] " overwrite
    if [[ ! "$overwrite" =~ ^[Yy] ]]; then
        echo "Keeping existing .env. Run ./start.sh to launch."
        exit 0
    fi
fi

# Check prerequisites
echo "Checking prerequisites..."
missing=()
command -v docker >/dev/null 2>&1 || missing+=("docker")
command -v docker compose version >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 || missing+=("docker-compose")

if [ ${#missing[@]} -gt 0 ]; then
    echo "ERROR: Missing required tools: ${missing[*]}"
    echo "Install Docker and try again."
    exit 1
fi
echo "  docker ✓"
echo "  docker compose ✓"
echo ""

# Collect configuration
echo "--- LucidLink Configuration ---"
echo ""
read -rp "LucidLink Service Account token (sa_live:...): " ll_token
echo ""

echo "--- MinIO / S3 Storage (optional, for creating filespaces) ---"
echo "Leave blank to skip."
echo ""
read -rp "MinIO endpoint URL (e.g. https://my-nas.tail1234.ts.net): " minio_endpoint
if [ -n "$minio_endpoint" ]; then
    read -rp "MinIO bucket name [lucidlink]: " minio_bucket
    minio_bucket=${minio_bucket:-lucidlink}
    read -rp "MinIO access key: " minio_access_key
    read -rsp "MinIO secret key: " minio_secret_key
    echo ""
    read -rp "MinIO region [us-east-1]: " minio_region
    minio_region=${minio_region:-us-east-1}
fi

# Write .env
cat > .env <<ENVEOF
# LucidLink Workspace Manager — generated by setup.sh
LUCIDLINK_TOKEN=${ll_token}

# MinIO / S3 storage defaults
MINIO_ENDPOINT=${minio_endpoint:-}
MINIO_BUCKET=${minio_bucket:-lucidlink}
MINIO_ACCESS_KEY=${minio_access_key:-}
MINIO_SECRET_KEY=${minio_secret_key:-}
MINIO_REGION=${minio_region:-us-east-1}
ENVEOF

echo ""
echo ".env written."
echo ""

# Tailscale Funnel setup
echo "--- Tailscale Funnel (optional) ---"
read -rp "Set up Tailscale Funnel to expose the API publicly? [y/N] " setup_funnel
if [[ "$setup_funnel" =~ ^[Yy] ]]; then
    if ! command -v tailscale >/dev/null 2>&1; then
        echo "WARNING: tailscale CLI not found. Skipping funnel setup."
    else
        read -rp "HTTPS port for the API [443]: " funnel_port
        funnel_port=${funnel_port:-443}
        echo "Running: tailscale funnel --bg --https=${funnel_port} http://localhost:8000"
        tailscale funnel --bg --https="${funnel_port}" http://localhost:8000 || \
            sudo tailscale funnel --bg --https="${funnel_port}" http://localhost:8000 || \
            echo "WARNING: Funnel setup failed. You can configure it manually later."
    fi
fi

echo ""
echo "============================================"
echo "  Setup complete!"
echo ""
echo "  Start the services:  ./start.sh"
echo "  Or manually:         docker compose up -d"
echo "============================================"
